# Generated by Django 4.1.6 on 2023-02-28 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=100)),
                ('langdesc', models.TextField(default='')),
                ('langimg', models.ImageField(default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ReadGenre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=100)),
                ('gendesc', models.TextField(default='')),
                ('genimg', models.ImageField(default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Reads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
                ('audio', models.FileField(upload_to='audio/')),
                ('is_active', models.BooleanField(default=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visionapp.readgenre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visionapp.language')),
            ],
        ),
    ]
