# Generated by Django 4.1.6 on 2023-03-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reads',
            name='audio',
            field=models.FileField(unique=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='reads',
            name='author',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='reads',
            name='img',
            field=models.ImageField(unique=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='reads',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
