# Generated by Django 4.1.6 on 2023-02-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('publisher', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='login_detailes',
        ),
    ]
