# Generated by Django 4.1.6 on 2023-02-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionapp', '0002_book_delete_login_detailes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
                ('genre', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='audio/')),
            ],
        ),
        migrations.DeleteModel(
            name='book',
        ),
    ]
