# Generated by Django 4.1.6 on 2023-02-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visionapp', '0003_read_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadGenre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='read',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='read',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visionapp.readgenre'),
        ),
    ]
